### ISSUE TITLE
 Wikilinks: link-transform

### ISSUE THREAD

**Issue by klml** [neurobin/mdx_wikilink_plus#1]
I would like to have an option to change the link-transform.

Currently the link is created according to the text notation: `[[Wiki Link]]` produces `href="/Wiki_Link/"`

I would like to have the possibility to lowercase the link: `[[Wiki Link]]` should produce `href="/wiki_link/"` (and for the sake of completeness: uppercase;)

Is this in the scope of wikilink_plus? So I would create an PR.

I proposed this already on [Python-Markdown](https://github.com/Python-Markdown/markdown/issues/875), but it was out of scope.

**Comment by neurobin** [comment]
sure, you can make the PR.

**Comment by neurobin** [comment]
PR has been merged. Thanks.
