### ISSUE TITLE
README.md: doublicate code

### ISSUE THREAD

**Issue by klml** [neurobin/mdx_wikilink_plus#3]
There is some code for tests and build_url, copied in the [README.md](/neurobin/mdx_wikilink_plus/blob/master/README.md).
I think it will be better using links like [build_url](/neurobin/mdx_wikilink_plus/blob/master/mdx_wikilink_plus/mdx_wikilink_plus.py#L36)

**Comment by neurobin** [comment]
Used the link for build_url. But other codes in readme is related to the specific output. It doesn't have to have any relation with the tests.
